server:
  port: 8100
logging:
  level:
    auth.service: DEBUG
    org:
      springframework:
        security: DEBUG
spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: ${AUTH_DB_URI:jdbc:postgresql://localhost:5432/}
    username: ${AUTH_DB_USER:postgres}
    password: ${AUTH_DB_PSWD:rootroot}
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
application:
  security:
    accessToken:
      secret: ${AUTH_TOKEN_SECRET:token-secret}
      expire: ${AUTH_TOKEN_EXPIRE:3600000}
    refreshToken:
      secret: ${REFRESH_AUTH_TOKEN_SECRET:refresh-token-secret}
      expire: ${REFRESH_AUTH_TOKEN_EXPIRE:86400000}
  admin:
    email: ${ADMIN_EMAIL:admin@admin.ru}
    firstName: ${ADMIN_FIRST_NAME:admin}
    lastName: ${ADMIN_LAST_NAME:admin}
    phoneNumber: ${ADMIN_PHONE:88005553535}
    password: ${ADMIN_PSWD:Administrator42}